version: 2
jobs:
      dawn:
            docker:
                  - image: gtclang/dawn-env-ubuntu19.10
            steps:
                  - checkout:
                          path: /usr/src/dawn
                  - run:
                          name: Something
                          command: cat /etc/*release
